### ISSUE TITLE
荣耀5X手机，点录视频的按钮没有反应，然后使用其他的点击事件，就会崩

### ISSUE THREAD

**Issue by happyCoding12138** [Werb/MediaUtils#2]
错误日志如下：

 Exception dispatching input event.
 Exception in MessageQueue callback: handleReceiveCallback
java.lang.RuntimeException: getParameters failed (empty parameters)
at android.hardware.Camera.native_getParameters(Native Method)
at android.hardware.Camera.getParameters(Camera.java:2124)
at com.kanq.camera.MediaUtils.setZoom(MediaUtils.java:329)
at com.kanq.camera.MediaUtils.access$1(MediaUtils.java:327)
at com.kanq.camera.MediaUtils$ZoomGestureListener.onDoubleTap(MediaUtils.java:317)
at android.view.GestureDetector.onTouchEvent(GestureDetector.java:523)
at com.kanq.camera.MediaUtils$1.onTouch(MediaUtils.java:85)
at android.view.View.dispatchTouchEvent(View.java:8548)
at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2408)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2050)
at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2408)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2050)
at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2408)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2050)
at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2408)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2050)
at com.android.internal.policy.impl.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:2390)
at com.android.internal.policy.impl.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1734)
at android.app.Activity.dispatchTouchEvent(Activity.java:2838)
at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:2351)

**Comment by happyCoding12138** [comment]
我解决了，存文件到华为手机外置存储卡，就会出问题。操蛋的华为手机

**Comment by werbhelius** [comment]
😁
